### ISSUE TITLE
My emojis in the are ignored and are still shown

### ISSUE THREAD

**Issue by pinkachoo** [FrostCo/AdvancedProfanityFilter#344]
Trying to delete sorry... I'm still working on it.

**Comment by richardfrost** [comment]
Hello @pinkachoo! Your request was totally fine. Do you still have a question on filtering emojis?

**Comment by richardfrost** [comment]
@pinkachoo Emojis are supported, but sometimes there are weird issues that can crop up with them. The most likely reason that they aren't working is if you have the "word" (emoji) set to `Exact` match method. That means they will only be filtered if there are no other characters around them. If there are emojis you never want to see, I would recommend setting the match method to `Partial`, which can be done in Options > Word tab one at a time, or in the Bulk editor on that same page.

Let me know if you need any more help, or have any questions. Thanks!
