### ISSUE TITLE
HBO Max Audio Filtering not working

### ISSUE THREAD

**Issue by simpledn** [FrostCo/AdvancedProfanityFilter#347]
Text filtering works great, but audio filtering isn't. I've tried switching to tab and video volume with no effect. Do I need to restart chrome each time I change?

**Comment by richardfrost** [comment]
Thanks for pointing the issue out. There have been some changes on HBO Max that have indeed broken the muting function for some videos. I have a partial fix that I'm hoping to get out in the next day or two. It should work, but it doesn't have the ability to hide the captions/subtitles anymore. That will take me some more time to work out, but at least the muting can start working again. I'll let you know when the I publish the update.

**Comment by richardfrost** [comment]
@simpledn Version [2.25.1](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.25.1) has been released now. If you don't have it yet, just restart your browser and you should get the update.

This version should enable the muting again in HBO Max, but like I mentioned earlier, hiding the caption text isn't going to work yet.

If you (or anyone reading this) get a chance to test it out, let me know how it works for you!

**Comment by acougle** [comment]
Having trouble with HBOMax again. Have version 2.28 APF and with it set to normal or deep, it filters text but not audio on the new Matrix movie and I Am Number Four. Thanks for your help!

**Comment by richardfrost** [comment]
@acougle Sorry for being so slow at getting to this. Still playing catch-up after the holidays.

I've received reports from a few others about HBO Max as well. I'll try taking a look at it tonight and see what changed, and then I'll update when I have a better idea of when to expect a fix.

**Comment by richardfrost** [comment]
@acougle @simpledn Just wanted to check in and see if the latest version is working for you now?
