### ISSUE TITLE
Spaces ignored when deciding how to censor a word.

### ISSUE THREAD

**Issue by JamieRCHI** [FrostCo/AdvancedProfanityFilter#420]
#### :bug: Description
With 'omg' censored, 'om g' is  changed to 'xxx'.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Add 'omg' to the words to be censored.
2. Enable replace with 'xxx'.
3. Refresh this page and look at my comments.

#### :heavy_check_mark: Expected behavior
I should see 'from growing' not 'frxxxrowing'.
I would expect your code to Not ignore spaces on the web page when comparing with words in my 'blacklist'.
(Unless I am missing a setting that is. In that case 'my bad'.)

#### :computer: Details
 - **OS:** Windows 10
 - **Browser:** Firefox
 - **Browser Version:** 102.0
 - **Affected site(s):** All websites.

**Comment by richardfrost** [comment]
No worries @JamieRCHI, thanks for responding. Currently there is not a way to customize which separators or matched, and right now it includes `-`, `_`, and ` `. It isn't always helpful, but in some cases it can be, which is why it is usually off by default. Take care!
