### ISSUE TITLE
Browser Audio Censoring Not Working

### ISSUE THREAD

**Issue by Kcirezmai** [FrostCo/AdvancedProfanityFilter#461]
Hello, 

I hope all is well. I’ve purchased the APF app and I am unable to get it to work. Please help.

Helpful information:

1. iPad Pro 2020 model running iOS 16.1.1
2. Safari browser
3. Netflix and Amazon Prime Video
4. Followed all the instructions in the help file
5. Works on the closed captioning 
6. Desktop version works very well after some tweaks 

Thank you for such a great tool.

**Comment by richardfrost** [comment]
Hi @Kcirezmai,

I'll see if I can get my hands on an iPad Pro to test with today, but if not I can probably use a simulator.

In the meantime I have a couple questions:
- Which country are you accessing from? Several of the streaming services have different capabilities/limitations based on where its being streamed from.
- Do any other sites work? YouTube might be the easiest to confirm with. Also, you can test muting by temporarily adding a non-profane word to your wordlist if you'd like.

**Comment by richardfrost** [comment]
If you are still having this issue, could you answer the questions above @Kcirezmai? It seems like its working like I'd expect in my simulator, but that doesn't necessarily mean it translates to a real device.
