### ISSUE TITLE
"Filter text" deselects active word

### ISSUE THREAD

**Issue by CreeperPookie** [FrostCo/AdvancedProfanityFilter#466]
#### :bug: Description
The main issue is that if you have a word selected and decide to click the `Filter text` checkbox, it unselects the word, causing you to potentially have to find it in the list again.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. In the wordlist, select any word.
2. Click on `Filter text` (the current checkbox state doesn't matter)
3. Current word deselects.

#### :heavy_check_mark: Expected behavior
Although this is a very minor issue, it should probably filter/unfilter the text in the selection, but keep the current selection.

#### :computer: Details
 - **Device:** Dell Inspiron 17-7779
 - **OS:** Windows 11 Insider
 - **Browser:** Microsoft Edge (Chromium), with manifest v3
 - **Browser Version:** 108.0.1462.46
 - **Affected site(s):** N/A

#### :pencil: Additional context
Although there isn't a good reason why you would click the checkbox after selecting a word, an accidental click could cause you to have to re-type a substitution for a word. Also, I believe this issue was referenced in the first comment of issue #322, although I'm not completely certain.

**Comment by richardfrost** [comment]
This has been included in version [2.40.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.40.0). Feel free to comment here if you have any feedback for this update.

**Comment by richardfrost** [comment]
This has been included in version [2.40.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.40.0). Feel free to comment here if you have any feedback for this update.
