### ISSUE TITLE
Change 'whitelist' to 'allowlist'

### ISSUE THREAD

**Issue by throwaway-d** [FrostCo/AdvancedProfanityFilter#468]
It causes the assumption that black is bad.
- https://en.wikipedia.org/wiki/Whitelist#Controversy
- https://en.wikipedia.org/wiki/Blacklisting#Controversy

**Comment by richardfrost** [comment]
This has been included in version [2.40.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/2.40.0). Feel free to comment here if you have any feedback for this update.

**Comment by throwaway-d** [comment]
Very awesome! :D
![image](https://user-images.githubusercontent.com/121148372/212296706-0e596f05-4283-486b-a858-9351937bbdb7.png)
