### ISSUE TITLE
Extension doesn't censor words in Ko-Fi posts

### ISSUE THREAD

**Issue by RiffyDiffy** [FrostCo/AdvancedProfanityFilter#483]
#### :bug: Description
No, this is not one of my "extension turned on but doesn't censor" bug reports. When going to a post in Ko-Fi, strangely, Advanced Profanity Filter does not censor out the words. Yes, for the last time, I turned on my extension, and it blocks words site-wide, but not Ko-Fi's posts.

#### :twisted_rightwards_arrows: Steps To Reproduce
Go to any posts that has any kind of extreme vulgarity. [Here's an example (+18).](https://ko-fi.com/post/Fuck-it-O4O36EI1K)

#### :heavy_check_mark: Expected behavior
Everyone knows what will happen, but I'll say it, right here: I expected the post to be censored. Done.

#### :computer: Details
 - **Device:** HP Pavilion Desktop TP01-2165z
 - **OS:** Windows 11 Home Insider Preview Build 25267.1000
 - **Browser:** Vivaldi
 - **Browser Version:** 5.6.2867.62 (Stable channel)
 - **Affected site(s):** Ko-Fi posts

**Comment by richardfrost** [comment]
Thanks for the report. This site appears to use Shadow DOM for content quite a bit, which can cause issues with filtering. Does it work correctly for you if you set APF's filter mode to `Deep`?.

![image](https://user-images.githubusercontent.com/1507205/216674646-6dd1ccf7-3aea-40d9-902b-bc709a28c3a7.png)

**Comment by RiffyDiffy** [comment]
> Thanks for the report. This site appears to use Shadow DOM for content quite a bit, which can cause issues with filtering. Does it work correctly for you if you set APF's filter mode to `Deep`?.
> 
> ![image](https://user-images.githubusercontent.com/1507205/216674646-6dd1ccf7-3aea-40d9-902b-bc709a28c3a7.png)

Works now. Thanks!

**Comment by richardfrost** [comment]
Nice! I'm glad its working for you now. APF should remember the filter mode for that domain, so once you have it set you shouldn't have to worry about it again.
