### ISSUE TITLE
Can't install on Yandex browser mobile. 

### ISSUE THREAD

**Issue by tonyram57** [FrostCo/AdvancedProfanityFilter#487]
I got a new phone and the first thing I did was install APF extension in Kiwi Browser. However when I tried to install it in Yandex browser it said it was not compatible.

I tried a old version of the browser which did not work. I tried sideloading it by extracting the .json file but that failed.  I know I can use Kiwi but some pages are broken and only work in Yandex browser. 

I however got it installed in Firefox beta after carefully following the instructions that were provided.

**Comment by tonyram57** [comment]
I just try to install the version from the play store.
https://chrome.google.com/webstore/detail/advanced-profanity-filter/piajkpdbaniagacofgklljacgjhefjeh

**Comment by richardfrost** [comment]
Interesting. So when I try to install it I get the following message:

```Chrome of version at least 88 is required```

I don't have a specific version marked as required, so I'm guessing it is being dictated by features the extension is using. I also tried manually installing an unpacked extension, but it just fails saying the `manifest.json` is invalid.

Could you check which version of APF your old phone or tablet are on @tonyram57? I'm going to be pretty short on time the next few weeks, but I'll try and dig in deeper to the issue as I'm able.

**Comment by tonyram57** [comment]
Version on my fire tablet is 3.0.2.  As I said I tried everything to install it and it just refuses to install on Yandex browser, both the v2 and v3 versions. What is really annoying is that I can't export my settings without rooting my device. Both one plus clone and Google backup restored nothing.

As I said it works fine if you installed it when it was comparable but if you ever removed it or reinstall Yandex you can no longer use the extention. I since replaced it with Firefox beta.

**Comment by richardfrost** [comment]
I'm going to close this due to inactivity, and that I haven't made any progress on it. If anyone is still looking to use this and running into trouble feel free to re-open or comment.
