### ISSUE TITLE
Feature regression - filter hijacks textboxes while typing words

### ISSUE THREAD

**Issue by hummy123** [FrostCo/AdvancedProfanityFilter#489]
Hi there. Thanks for the helpful extension. The recent update caused some issues that didn't exist before.

#### :bug: Description
When logging into Twitter and typing a tweet, if one types a word that contains a blacklisted word (such as "hell" in order to spell "hello"), the text cursor jumps to the start of the input and typing any letters after that sends the letters to the start of the input instead of where the selection was which makes typing a tweet impossible. This did not happen before the update.

I have uploaded a short video to demonstrate the issue. First, I try typing "hello, my name is humza" in Twitter where the issue persists and then in Gitpod which has a smaller problem (one I don't care about) and then in Google which uses a standard <input> instead of a <div> and doesn't have a problem at all.

I hope since this is a feature regression that it won't be considered too minor of an issue.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to Twitter.
2. Compose a new tweet.
3. Type part of a blacklisted word (like "hell" for "hello").
4. Continue typing. You will see you typed something incomprehensible.

#### :camera: Video
https://drive.google.com/file/d/1uZAXMG0LcaXypl640nVOidGe3mOZZq_t/view?usp=share_link

#### :computer: Details
 - **Device:** Laptop
 - **OS:** Linux (Pop!OS)
 - **Browser:** Firefox
 - **Browser Version:** 103.0
 - **Affected site(s):** twitter.com

**Comment by richardfrost** [comment]
Hi @hummy123, thanks so much for reporting the issue. Its definitely a bug, and is not a minor issue. I'll get an update published as soon as I can. Thanks for sharing all those details and examples, it really helped. The new release should fix Twitter (and probably countless other sites), but Gitpod will likely not be fixed with it. I would probably recommend just disabling APF on that domain to avoid any issues there.

**Comment by hummy123** [comment]
> @hummy123, this has been included in version [3.0.2](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/3.0.2). Feel free to comment here if you have any feedback for this update.
> 
> It should be available for Firefox now, and the other store fronts should update as soon as their review process is complete.

@richardfrost That was fast! I didn't expect you to fix it so quickly.  It's much appreciated.

I don't use Gitpod personally (was just trying to test the extension on different input boxes) but I can see how it's still an issue you'd like to fix some time. 

Twitter's text box works as it did before according to my tests, which I appreciate. Thanks again.

**Comment by richardfrost** [comment]
@hummy123 thanks for reporting back! I'm glad I was able to get it resolved quickly for you. I'll add looking into Gitpod into the backlog. Take care!
