### ISSUE TITLE
Crunchyroll Muting Not Working

### ISSUE THREAD

**Issue by Commonman7** [FrostCo/AdvancedProfanityFilter#491]
Crunchyroll has stopped filtering since your last update

**Comment by richardfrost** [comment]
Thanks for reporting the issue @Commonman7. I think I've identified the issue and should have a fix out in a day or two.

**Comment by Commonman7** [comment]
Thank you sir. Your hard work is greatly appreciated.

**Comment by richardfrost** [comment]
This has been included in version [3.0.3](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/3.0.3). Feel free to comment here if you have any feedback for this update.

**Comment by Commonman7** [comment]
Sorry, but when will the new version be available for download on chrome
store? It still shows version 3.0.2?

Thank you

**Comment by richardfrost** [comment]
@Commonman7 I submitted it a couple days ago for review, but unfortunately we'll just have to wait for their review process before it gets published. Hopefully pretty soon, but they do say they can take up to 30 days.

**Comment by Commonman7** [comment]
Ok. I appreciate the update.

Thank you

**Comment by richardfrost** [comment]
Yep, no problem. If you are wanting to test it earlier, APF version 3.0.3 is available for Firefox now @Commonman7.

**Comment by Commonman7** [comment]
Great. I’ll check it out tonight

**Comment by Commonman7** [comment]
I tried it out and it seems to be working fine.

**Comment by richardfrost** [comment]
Thanks for reporting back @Commonman7. It looks like Chrome has approved the update now, so it should be there too.
