### ISSUE TITLE
Redbox Audio & Caption filtering not working

### ISSUE THREAD

**Issue by bdc0der** [FrostCo/AdvancedProfanityFilter#493]
#### :bug: Description
The extension doesn't filter text or audio at Redbox.com

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to redbox.com
2. Open any on-demand movie 
3. Use the extension, words on the filter list are not filtered in the audio or text for Redbox.

#### :heavy_check_mark: Expected behavior
The extension should mute the audio and censor the captions.

#### :camera: Screenshots
N/A

#### :computer: Details
 - **Device:** [MacBook Laptop, Windows Deskstop]
 - **OS:** [MacOS 12.6.3, Windows 10]
 - **Browser:** [Firefox & Chrome]
 - **Browser Version:** [e.g. 111]
 - **Affected site(s):** [www.redbox.com]

#### :pencil: Additional context
I am pretty sure this is a problem with the extension, not the browser. The extension's popup is green when the captions that should be filtered appear. This isn't working on either device I have tried, both with the extension and browser default settings. Because of this, I believe that this is a problem with either the extension or some sort of setting within Redbox. (The latter case could be similar to the Netflix muting problem I had months ago)

**Comment by richardfrost** [comment]
Thanks for reporting the issue @bdc0der. Could you give this updated config a try and see how it works?

```json
{
  "www.redbox.com": [
    {
      "mode": "elementChild",
      "parentSelector": "div.rb-text-container",
      "subtitleSelector": "SPAN",
      "tagName": "DIV"
    }
  ]
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

For best results, make sure to remove any custom config used for testing like this once its been included in the official update.

**Comment by bdc0der** [comment]
Sorry I wasn't able to get back, my email wasn't working for awhile. The latest version still does not appear to be working on Redbox, for Windows 10 on ChromeOS. I'll check out to see if it's a local problem by testing it on other devices, but I can't find anything that might interfere with its ability to filter.

**Comment by bdc0der** [comment]
Tested it on my Mac and other devices, and it still does not appear to be working. Any thoughts?

**Comment by richardfrost** [comment]
Thanks for reporting back @bdc0der, and for all your testing.

I should be able to take a look tonight. Are you using any "custom config", or is it just using the built-in site config? Also, could you share the name of a video or two you are testing with? I'll probably start with testing an free on-demand one. Hopefully they'll use the same caption/subtitle format for both free and paid, but we'll see.

**Comment by bdc0der** [comment]
I am only using the built-in config, and I'm testing it on The Lost City, at the 4:03 mark, and I have verified the word is in my filter list.

**Comment by richardfrost** [comment]
Thanks for sharing the example @bdc0der. I think I finally have a universal fix for Redbox now. I had to make some code changes, so give it a try once you get version [3.2.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/3.2.0). Make sure to remove any custom sites config for Redbox when checking it.

Firefox has already updated, and I expect Chrome will approve it in the next 24 hours, and Edge will probably be within the next 72 hours or so.

**Comment by bdc0der** [comment]
Testing it on a brand new browser profile (for Firefox), it appears to be working. Many thanks for helping. As for the actual browsers I use, I'll try to find out if it's a problem with an extension or something. Thanks for the help, I'll get back when I find the issue.

**Comment by bdc0der** [comment]
Well, from what I can tell, it doesn't seem to be a problem with any extension I'm using. That narrows it down to either a specific function for APF, or the browser.

**Comment by bdc0der** [comment]
Alright, I found the problem. I forgot to get rid of the config you had given me earlier. Thank you so much for your help, really appreciate it. I'll just test to make sure it works on my main browser, and then I'll close the issue

**Comment by bdc0der** [comment]
Alright, I tested it on Chrome, and it worked perfectly. Thanks for sticking with this, and helping fix the issue. Best of luck with the continued progress of the extension!

**Comment by richardfrost** [comment]
Awesome, glad to hear it! Thanks for reporting back, and for your patience with the issue. Take care @bdc0der!
