### ISSUE TITLE
Youtube muting not working

### ISSUE THREAD

**Issue by WolfD1g1tal** [FrostCo/AdvancedProfanityFilter#508]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like)._

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to '...' [Youtube](https://www.youtube.com/)
2. Click on '....'cc

#### :heavy_check_mark: Expected behavior
I use it to block blasphamey mostly. 

#### :camera: Screenshots
![Screenshot_19a](https://github.com/FrostCo/AdvancedProfanityFilter/assets/117151099/64c630c9-3f6e-4058-bf8b-44afc6ae0181)

#### :computer: Details
 - **Device:** [e.g. MacBook Pro, Google Pixel] _PC_
 - **OS:** [e.g. MacOS 10.14, Windows 10] _Windows 10_
 - **Browser:** [e.g. Chrome, Firefox] _Chrome_
 - **Browser Version:** [e.g. 50]  _Chrome is up to date
Version 116.0.5845.97 (Official Build) (64-bit)_
 - **Affected site(s):** [e.g. www.google.com] Youtube.com

#### :pencil: Additional context
when i try to slide the program to on i get a black circle with line through it it also does it on mode /filter/ text
sometimes when i look at the extension details in chrome it will show an error:
Unchecked runtime.lastError: Cannot create item with duplicate id addSelection
Context
Unknown
Stack Trace
:0 (anonymous function)
Nothing to see here, move along.
Unchecked runtime.lastError: Cannot create item with duplicate id removeSelection
Unchecked runtime.lastError: Cannot create item with duplicate id disableTabOnce
Unchecked runtime.lastError: Cannot create item with duplicate id toggleTabDisable
Unchecked runtime.lastError: Cannot create item with duplicate id toggleForDomain
Unchecked runtime.lastError: Cannot create item with duplicate id toggleAdvancedForDomain
Unchecked runtime.lastError: Cannot create item with duplicate id toggleFramesForDomain
Unchecked runtime.lastError: Cannot create item with duplicate id options

Any help i can give please contact me. Thanks in advance brother.

**Comment by richardfrost** [comment]
Sorry its not working for you @WolfD1g1tal. I can't seem to replicate the issue unfortunately. Could you send me a copy of your config?

To export/backup your config go the extension's Options page > Config tab and click the "Export" button. It will then save your config as a file that you can backup or share.

Feel free to attach it here, or send it to me in an email. This will allow me to better replicate your situation and hopefully we can get to the bottom of the issue.

**Comment by richardfrost** [comment]
Just checking in @WolfD1g1tal to see if this is still an issue for you, or if it was resolved or you moved on. Thanks!

**Comment by richardfrost** [comment]
I'm going to close this, but if you still have issues with it @WolfD1g1tal feel free to open it again and share any additional details you have.
