### ISSUE TITLE
Not working on this site using certain capital font. 

### ISSUE THREAD

**Issue by tonyram57** [FrostCo/AdvancedProfanityFilter#509]
I really don't want to post the site since it's adult site but I have to since it's not working with this type of font.
(REDACTED)
You can see the f-word and other swears are filtered with the normal font but with the more capital font the f-word is not filtered at all.

**Comment by richardfrost** [comment]
I won't be able to check out the full site, but I did take a quick peek with all media disabled on my browser. and I am not seeing an example of what you were describing. Could you share a screenshot of an element using the browser's dev tools? Without being able to see the page's structure I'm not sure why it isn't working.

Did you try using the "Advanced" or "Deep" modes on the page? If not, maybe give those a try and let me know if that works for you.

**Comment by tonyram57** [comment]
Thanks so much for redacting the link. I wanted to delete the post. I since don't bother to visit that page since it's the only one giving me problems and it's some kind of funky font that causes issues probably not a standard html font but a emoticon font or something. Any

**Comment by richardfrost** [comment]
Thanks @tonyram57, I'm glad that the extension is working well for you on other sites! Take care!
