### ISSUE TITLE
Filter not filtering one word in the list

### ISSUE THREAD

**Issue by Jrad337** [FrostCo/AdvancedProfanityFilter#515]
I just encountered a problem that I can't resolve.
The filter stopped filtering one four letter word in the word list. I deleted the extension and reinstalled it I tried resetting the settings to default and nothing will fix it.

![20231007_215052](https://github.com/FrostCo/AdvancedProfanityFilter/assets/111664285/97772d41-42ee-431b-81f0-b834489274b7)

The screenshot is of what the filter did. It got rid of the last two letters of the word but it did not mute the audio. And it is only that word. The filter works great with all the other words.

The extension is on Chrome. I am running Windows 11 on an HP Desktop PC.

**Comment by richardfrost** [comment]
Hi @Jrad337, sorry it has stopped working for you. Which service is that that has the issue?

**Comment by Jrad337** [comment]
The service I'm using is Netflix
But once again it is only the one word for some reason. It doesn't matter
what derivative of the word comes up it will never filter s h i t.
When I first saw the problem it was a derivative (Bullshit]. So I added
that word completely but then I realized the word s h i t was a partial
match so it should have filtered it and then I saw it it never filters that
word it only filters the last to letters [it] in the captions and doesn't
mute the audio. Thanks so much for responding. You have the best help
available for any app I've ever seen.

-Jared

**Comment by Jrad337** [comment]
Update. Just watched a different show that has that word and it muted the
audio and it censored h i t instead of just i t. The show that it is not
working on is "Suits" the show that it does work on is "Away"

**Comment by richardfrost** [comment]
Thanks for those extra details @Jrad337, and for the compliment. I try to be as helpful as I can be.

Anyway, in this particular case, unfortunately it looks like Netflix (or whoever provided the captions) pre-filtered the text. If you watch it without APF running at all it will still show "HOLY SH--". If this is a common occurrence for this show, or if you'd like the filter to catch this one specific instance, I'd recommend adding a new word to the filter:

- Word: `sh--` 
  - Match Method: `Exact`
  - Match repeated characters: `Unchecked`
  - Match separators: `Unchecked`
  
This worked for me at ~28:25 in Suits S03E14.

**Comment by Jrad337** [comment]
that was it! you got it, thank you so much!

**Comment by richardfrost** [comment]
You're welcome!
