### ISSUE TITLE
Feature Request: Make Firefox plugin compatible with upcoming Firefox Android full extensions support

### ISSUE THREAD

**Issue by BenJamesAndo** [FrostCo/AdvancedProfanityFilter#522]
Firefox will be allowing any extension from their store to be installed on the Firefox Android app [in December](https://blog.mozilla.org/addons/2023/11/01/is-your-extension-ready-for-firefox-for-android/). The current beta release supports this functionality. Currently you could only install a small number of extensions. However in order to easily allow your extension to be installed for Android there's a few changes you have to make. It's outlined [here](https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/).

Although, with the beta release I was able to add this extension by loading the desktop view of the extensions store and installing it. I'm happy to say it works really well :) But obviously tagging it correctly would make it easier to install.

**Comment by richardfrost** [comment]
Thanks for the info @BenJamesAndo. I'll take a look at it and try to have everything in place before December.

**Comment by richardfrost** [comment]
@BenJamesAndo I think everything that is needed should be there in the latest version, [3.3.2](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/3.3.2). If you get a chance to test it out let me know how it works for you.

**Comment by BenJamesAndo** [comment]
Tested and works great, thank you!
The settings area could do with being more mobile responsive, but that would be a separate feature request.
Functionally it all seems to work really well. Cheers.
