### ISSUE TITLE
Audio Muting Site Request Data (www.flixwave.to) 

### ISSUE THREAD

**Issue by Jo7777** [FrostCo/AdvancedProfanityFilter#524]
_Instructions: This template is written in Markdown. Click the "Preview" tab to see what it will look like when submitted. Fill in the applicable sections (you can erase the examples if you'd like). For more information, please see [this page](https://github.com/FrostCo/AdvancedProfanityFilter/wiki/New-Audio-Muting-Site)._

#### 🎥 The Site
_Example: www.flixwave.to

#### :speech_balloon: Subtitle Element/Node
_Example:_
```html
<div class="jw-text-track-container jw-reset" style="position: absolute; inset: 0px; margin: 1.5%;"><div class="jw-text-track-display jw-reset" style="text-align: center; white-space: pre-line; position: absolute; direction: ltr; writing-mode: horizontal-tb; unicode-bidi: plaintext; left: 230.263px; top: 163.2px; bottom: 23.5px; height: 22.5px;"><div class="jw-text-track-cue jw-reset" style="position: relative; padding-left: 0px; padding-right: 0px; left: 0px; top: 0px; bottom: 0px; display: inline; white-space: pre; writing-mode: horizontal-tb; unicode-bidi: plaintext;">What the fuck!</div></div></div>
![Screenshot 2023-11-22 165910](https://github.com/FrostCo/AdvancedProfanityFilter/assets/20398958/364092f0-0b34-4897-aca1-ecec7ff115a3)

```

#### :pencil: Additional notes
_Add any other context or screenshots about the request here._
![Screenshot 2023-11-22 165910](https://github.com/FrostCo/AdvancedProfanityFilter/assets/20398958/3bc98ca7-ea12-4fcf-87fa-0f245129af84)

**Comment by richardfrost** [comment]
Hey @Jo7777, sorry this took me so long to get around to it, but as this site is not an official streaming site I won't be able to include it in the extension.

You may have some success with using the config [here](https://github.com/FrostCo/AdvancedProfanityFilter/wiki/Audio-Muting:-Additional-Sites#site-flixwaveto) though.

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

**Comment by Jo7777** [comment]
Thanks for getting back to me. I will try it out.
