### ISSUE TITLE
New default filter suggestion

### ISSUE THREAD

**Issue by unforgettableid** [FrostCo/AdvancedProfanityFilter#541]
#### :loudspeaker: The Shortcoming
APF does not filter the string "WTF" by default.

#### :microscope: Describe the solution you'd like
APF could substitute it with the word "what".

#### Conclusion
Thank you for all the work you've put into APF!

**Comment by richardfrost** [comment]
Thanks for the suggestion @unforgettableid. I am glad that you are enjoying AFP and want to make it better. I think that seems like a fine suggestion. I'll do a bit of testing with it before making it a default, but I think it would be a nice addition.

**Comment by richardfrost** [comment]
This was added in Version [3.3.3](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/3.3.3).
