### ISSUE TITLE
Adding Hallmark Movies Now to default filters

### ISSUE THREAD

**Issue by aehgit** [FrostCo/AdvancedProfanityFilter#542]
Hello, can Hallmark Movies Now be added to the default filters? Thank you.

**Comment by aehgit** [comment]
BTW, thank you sooooooooooooooo much for all the hard work in developing this awesome tool. We are so grateful!

**Comment by richardfrost** [comment]
Hi @aehgit, thanks for the kind words, I'm so glad that you are enjoying it!

I have made an attempt at supporting Hallmark Movies Now, but I'd love to have you test it and confirm its working for you if you're willing:

```json
{
  "www.hmnow.com": {
    "className": "amp-caption-area",
    "mode": "element",
    "subtitleSelector": "div.amp-caption > p",
    "note": "Hallmark Movies Now",
    "tagName": "DIV"
  }
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

If it ends up working for you, I'll get it added to the official supported sites in the next version.

Thanks again for your support and suggestion to make the filter even better!

**Comment by aehgit** [comment]
Thank you so much, it is working great!
Have a wonderful day!

**Comment by richardfrost** [comment]
Thanks so much for getting reporting back @aehgit, I appreciate it! I'll make another note here once the new update has been released. Hope you have a great day too!

**Comment by richardfrost** [comment]
This was added in Version [3.3.3](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/3.3.3).

If you used the "Custom config" in this issue, its recommend to remove the custom config once it has been included in the official update.

**Comment by aehgit** [comment]
Hello, Robert -
Thank you so much for your update to the Hallmark channel - it is working
great. Would it be possible for you to give us a code or an update for Pure
Flix? The Url is: https://app.pureflix.com/
Thank you so much,
Eric & Amber Halleran

**Comment by richardfrost** [comment]
You're welcome @aehgit! Pure Flix (#441) was added in the newest version [3.4.0](https://github.com/richardfrost/AdvancedProfanityFilter/releases/tag/3.4.0).

**Comment by aehgit** [comment]
Awesome, thank you so much!

**Comment by richardfrost** [comment]
No problem @aehgit. Feel free to let me know how it goes for you when you have a chance to try it out.
