### ISSUE TITLE
Hulu main site not muting.

### ISSUE THREAD

**Issue by electronicsbyjulie** [FrostCo/AdvancedProfanityFilter#543]
#### :bug: Description
Audio doesn't mute on Hulu's main site.

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Go to Advanced Profanity Filter options
2. Click on Audio
3. Select Mute audio on supported video sites and any mute method
4. Go to hulu.com
5. Watch anything where a filtered word is spoken. The text is replaced but the audio doesn't mute.

#### :heavy_check_mark: Expected behavior
The audio would be muted while the filtered caption is on the screen.

#### :computer: Details
 - **Device:** Dell desktop computer
 - **OS:** Ubuntu 20.04
 - **Browser:** Chrome
 - **Browser Version:** 120.0.6099.129
 - **Affected site(s):** www.hulu.com

**Comment by richardfrost** [comment]
Hi @electronicsbyjulie, sorry the filter isn't working as expected on Hulu for you.

I just took a quick look at a couple movies and it seems to be working for me, but if you could maybe send me an example or two of where it isn't working for you I could check those too. When I tested it with the `Browser tab` mute method it worked as expected. I tried it on the movie "Mr. & Mrs. Smith". I added the word "tonight" to my word list (temporarily, for testing), and then skipped ahead to about 0:25:00 into the movie and it seemed to work just fine, if you want to see if that works for you.

Hulu does have a slightly more complicated setup for filtering than most other sites, so its possible you have come across a hole that will need to be addressed.

Thanks again for reporting the issue!

**Comment by electronicsbyjulie** [comment]
Hi @richardfrost , I was watching S1E5 of Ghosted: https://www.hulu.com/watch/b1dbaaa1-2af6-4f04-8cab-0dee2bd2c887

The filtered word is "need". 11:43 is where the word is spoken in the episode. I've retested by clearing out my word list and re-adding only the one specific word, replacing it with "****". It is still happening; it's filtered just fine in the caption but no audio mute on Browser Tab, Video Mute, or Video Volume settings.

**Comment by electronicsbyjulie** [comment]
So this is strange... just tried it on my Lenovo laptop. Same version of Ubuntu and same version of Chrome, except it's Chromium installed with snap instead of the regular desktop Chrome. On the laptop, the audio mute works great.

**Comment by richardfrost** [comment]
Interesting, so it works with Chromium installed with Snap, but not the regular Desktop Chrome (or did I get that backwards)? That is very strange. Is it working on other sites, such as YouTube on both systems? Another question, are you able to mute the tab/site when audio is playing by right-clicking on the tab and selecting "Mute site". This is very interesting,

**Comment by electronicsbyjulie** [comment]
It's not muting on YouTube in Chrome either. The mute site option on the context menu of the tab itself is working fine.

After installing Chromium with snap, it mutes YouTube in Chromium but still not Hulu.

On Firefox it mutes Hulu.

**Comment by richardfrost** [comment]
@electronicsbyjulie not sure if you're running into the same problem as they are in #544, but if you have a bit of time maybe give that new config in there a try and let me know if it changes anything for you on Hulu.

**Comment by electronicsbyjulie** [comment]
The custom config fixes the issue after restarting the browser.

Thank you!

**Comment by richardfrost** [comment]
This was added in Version [3.3.3](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/3.3.3).

If you used the "Custom config" in this issue, its recommend to remove the custom config once it has been included in the official update.
