### ISSUE TITLE
Hulu audio muting not working

### ISSUE THREAD

**Issue by bdc0der** [FrostCo/AdvancedProfanityFilter#544]
#### :bug: Description
The extension recognizes text from captions on Hulu, but it doesn't mute the audio when the text gets censored. 

#### :twisted_rightwards_arrows: Steps To Reproduce
1. Enable audio muting on APF
2. Go to Hulu
3. Example video: Life in Pieces S2 E22, timestamp 9:00 (12:13 minutes remaining)

#### :heavy_check_mark: Expected behavior
I expected the extension to censor the audio along with the text, but only the text censored

#### :camera: Screenshots
<img width="1418" alt="Screenshot 2024-02-06 at 7 43 31 PM" src="https://github.com/FrostCo/AdvancedProfanityFilter/assets/119639394/28b3dd90-27f1-4a29-b5bc-27c4ea2d3424">

#### :computer: Details
 - **Device:** [Macbook Pro & Windows Desktop]
 - **OS:** [Macos 13.6 & Windows 10]
 - **Browser:** [Firefox & Chrome]
 - **Browser Version:** [ Firefox: 122.0.1 | Chrome: 121.0.6167.140] (Both are 64-bit)
 - **Affected site(s):** [www.hulu.com]

#### :pencil: Additional context
Another user also reported this issue, so I tried to test the audio and edit this comment to make it easier for you. 

The problem originally occurred on a custom APF config on Chrome, and I tried installing APF on a brand-new Firefox profile. I have also tried all audio muting methods but the problem persisted. With the browser tab method selected, it appears I can mute the browser tab manually, which suggests the extension failed to do so. Hopefully this makes sense. 

(ignore the thing with only the UI being visible in the screenshot, it appears that Hulu not allowing me to capture video content)

**Comment by WolfD1g1tal** [comment]
Mine is not even activating on hulu. it doesn't even cloak the subtitles. 
![image](https://github.com/FrostCo/AdvancedProfanityFilter/assets/117151099/fcc1bf0b-4356-4fed-a26b-f6831be7a6aa)
Up to date chrome with windows 11. 
it just stoped working within the last week. dont meber what day. 
![image](https://github.com/FrostCo/AdvancedProfanityFilter/assets/117151099/d7c00be6-5d79-4783-b7d3-cc26151cc220)

**Comment by WolfD1g1tal** [comment]
simply going  to the page recreates it.

**Comment by richardfrost** [comment]
It looks like at least in the case of the episode of "Life in Pieces" that they are using a new format for their captions.

I don't have much time today, but here is a custom config that we could try on and I'd love to get some feedback from it:

```json
{
  "www.hulu.com": [
    {
      "displaySelector": "div.ClosedCaption",
      "iframe": false,
      "mode": "watcher",
      "note": "Hulu update 24-02",
      "parentSelector": "div.ClosedCaption div.CaptionBox"
    },
    {
      "className": "caption-text-box",
      "displaySelector": "div.caption-text-box",
      "mode": "element",
      "subtitleSelector": "p",
      "tagName": "DIV"
    },
    {
      "displaySelector": "div.CaptionBox",
      "mode": "elementChild",
      "parentSelector": "div.CaptionBox",
      "tagName": "P"
    }
  ]
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

Unfortunately with the way their subtitles appear to be working, at least on that episode I tried it looks like we'll have to fallback to the `watcher` method for now. There might be some brief flashes or flickers of captions when hiding them, and its also possible for unfiltered captions to briefly show up as well. I'll look into it more when I have time, but if either @WolfD1g1tal or @bdc0der have time to test this out and share how it goes I'd appreciate it.

**Comment by bdc0der** [comment]
I did rough tests on both browsers and devices, and the custom config appeared to fix the problem. I'll keep the issue open for a few more days (in case I encounter more problems, or you find a more certain fix for it), but for now, it works great. 

Many thanks for your continued support!

**Comment by WolfD1g1tal** [comment]
windows 11 chrome up to date seems to be working now. Looks like that was the fix. my number count is registering like about 3 filter actions for each 1. but it has been doing that on and off on several sites. Thanks heaps for the fix.

**Comment by TruSteel** [comment]
Windows 11, Chrome and APF,  all up to date. Tried different settings and nothing worked for me. Tubi, Max, Peacock and more work great but Hulu doesn't. Hope to see a fix soon. Thank you

**Comment by TruSteel** [comment]
Hi thank you, new config I got to work. ty for your help

**Comment by bdc0der** [comment]
Well after a few days of using Hulu, I can't say I've found any issues with the config, so I'll be closing the issue. Thanks again for your continued and quick support!

**Comment by richardfrost** [comment]
Thank you for reporting back @bdc0der, @WolfD1g1tal, & @TruSteel. I'll get this added into the next version.

For best results, make sure to remove any custom config used for testing like this once it has been included in the official update.

**Comment by richardfrost** [comment]
This was added in Version [3.3.3](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/3.3.3).

If you used the "Custom config" in this issue, its recommend to remove the custom config once it has been included in the official update.

**Comment by bdc0der** [comment]
Duly noted, thank you
