### ISSUE TITLE
Not censoring in The Verge comment section

### ISSUE THREAD

**Issue by Glodigit** [FrostCo/AdvancedProfanityFilter#555]
#### :bug: Description

For as long as The Verge's new site has existed, I've noticed that the extension doesn't censor any words in the comment section. It's the only site I know that has this issue.

#### :twisted_rightwards_arrows: Steps To Reproduce

1. Go to theverge.com
2. Click on an article with comments
3. Scroll down to find a comment with profanity

#### :computer: Details

- **Device:** 11600K PC and N100 2-in-1 Laptop
- **OS:** Windows 10 / 11
- **Browser:** Vivaldi / Edge
- **Browser Version:** Latest
- **Affected site(s):** www.theverge.com

**Comment by richardfrost** [comment]
Thanks for reporting the issue @Glodigit. I took a quick look at it, and it appears they are using the ShadowDom for their comments section. Could you try turning on "Deep" mode for The Verge?

![image](https://github.com/FrostCo/AdvancedProfanityFilter/assets/1507205/1ac89fc0-aca7-4b78-b204-03ec9f1c6ddf)

**Comment by richardfrost** [comment]
@Glodigit Thanks for sharing what worked for you. Like I said, based off of how they built their page (especially the comments), it will need to have `Deep` mode selected to work.
