### ISSUE TITLE
amazon prime video not muting audio

### ISSUE THREAD

**Issue by jorymadi** [FrostCo/AdvancedProfanityFilter#559]
As the title suggests, when I try using the filter with Amazon Prime on Chrome and Firefox, it won't mute the audio for any profanity.

I followed the instructions as closely as I could, and still nothing.

I'm not sure if I'm missing something, or if Prime Video changed something, since it's worked for me before

Thanks for any help!

**Comment by andrewrmcneill** [comment]
I'm also experiencing this issue with the Amazon Prime UK site. The filter captures the subtitle text but does not mute the audio.

If it's any help, I've identified a code snippet of subtitles but haven't had any success at turning it into a custom configuration:

<div class="f1iwgj00" dir="auto"><div style="text-align: center; justify-content: flex-end; width: 100%; left: 0%; bottom: 30px; display: flex; position: absolute; flex-direction: column;"><p style="width: 100%; margin: 0px; font-style: normal; font-weight: normal; font-size: 100%;"><span class="fbhsa9" style="background-color: rgba(0, 0, 0, 0);"><span class="atvwebplayersdk-captions-text f7j034j" style="background-color: rgba(0, 0, 0, 0.5); color: rgb(255, 255, 255); font-size: 32px;">♪ I swear to God<br>I've seen it all ♪</span></span></p></div></div>

Thanks for any help!

**Comment by acougle** [comment]
Amazon Prime has stopped being filtered (Netflix still is). Won't mute or substitute captions.

**Comment by richardfrost** [comment]
Thanks for all the reports. I'm going to look into it, but most likely Amazon has made a change to their site that is interfering with APF's ability to correctly identify captions/subtitles.

**Comment by richardfrost** [comment]
Sorry for the wait everyone (@jorymadi, @andrewrmcneill, @acougle), it took a bit more work than I expected to work through it. If anyone is available for trying something, please try the following config:

```json
{
  "www.amazon.com": [
    {
      "displaySelector": "div.atvwebplayersdk-captions-overlay",
      "iframe": false,
      "mode": "watcher",
      "parentSelector": "span.atvwebplayersdk-captions-text",
      "videoSelector": "div#dv-web-player video[src]"
    }
  ]
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

If you can test it and let me know how it goes that would be great!

**Comment by ITNerd79** [comment]
Just tested and it is working :)

**Comment by andrewrmcneill** [comment]
Amazing! Thank you, Richard - this works perfectly.

**Comment by ricktheartist** [comment]
Just tried it. It works again. Yay! Thank you Richard!

**Comment by jorymadi** [comment]
It's working for me too. Thanks!

**Comment by richardfrost** [comment]
Awesome! Thanks for all the reports everyone. Version [3.5.1](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/3.5.1) should now be available on most stores, so if you get the update you shouldn't need this custom config anymore. I recommend removing it so that you will get any future updates for Amazon as they get included in the extension. Thanks again for all the reports, it really helps!
