### ISSUE TITLE
Audio filtering has stopped working

### ISSUE THREAD

**Issue by joleona1982** [FrostCo/AdvancedProfanityFilter#560]
Hi

We use Advanced Profanity Filter every day to filter words when watching TV. It normally works really well, but it seems to have stopped working over the last few days. We've not changed any of the settings, but we can't seem to get it working again. The extension is on, and we have tried all of the available audio options, but the swear words are still audible. The words are still being filtered on the subtitles, so the extension is still active in some way. Is there anything that can be done? I've deleted the extension and re-downloaded, but that hasn't helped.

Thanks again
Jo

**Comment by richardfrost** [comment]
Hi @joleona1982, I'm glad that it normally works so well for you!

Right now we have a couple sites that are not working correctly (Amazon and Crunchyroll). Which site(s) are not working for you?

**Comment by joleona1982** [comment]
disney plus, amazon prime video (UK) and uktv. To be honest, it seems to be any and every site. But we first noticed it on amazon prime video (UK)

**Comment by ricktheartist** [comment]
@joleona1982 It can also matter which browser you are using. I just tried disneyplus using Chrome and it worked (both replacing the caption and muting the audio). But using Firefox it did not work, neither piece. For me though, both of those are US versions, not UK.

**Comment by joleona1982** [comment]
yeah i was using chrome

**Comment by richardfrost** [comment]
Thanks for the info @ricktheartist, I'll take a look at Disney+ as soon as I can in Firefox, but it will probably be a few days.

@joleona1982 

As for Amazon, I believe that I have a fix for it that you can apply now yourself [detailed here](https://github.com/FrostCo/AdvancedProfanityFilter/issues/559#issuecomment-2251851735), or wait until the update gets published.

**Comment by joleona1982** [comment]
Great thank you. We've been retesting various players and found that it
does now work with YouTube, netflix and Disney plus. Amazon prime video
still doesn't work, so I'll do as you've said. Thank you for your help

**Comment by TruSteel** [comment]
Disney Plus for me, when it mutes it says muted in chrome and firefox. I pasted an old config in to get it to work. Also Amazon was hit or miss on muting. Didn't work all the time.

**Comment by richardfrost** [comment]
Disney+ has updated their site again, and the latest config can be found in issue #595. This should now be fixed with version [4.0.0](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/4.0.0). If anyone is still having issues, please respond in #595.
