### ISSUE TITLE
Only mute audio

### ISSUE THREAD

**Issue by MrDizzyCam** [FrostCo/AdvancedProfanityFilter#570]
Hello,

When I try to use the extension on flixtor.li it gets disabled with a message  "Popup disabled by only mute audio". This happens whenever I try to activate the "only mute audio" option in profanity filter. 

The flixtor.li uses a VPN service, not sure if this has something to do with it. 

![Screenshot 2024-08-17 224541](https://github.com/user-attachments/assets/3f7ebe78-9197-4777-b7fb-ede400ef4647)

Anyway thank you for the brilliant extension, I use and enjoy it allot. 

Warm regards
Stephan

**Comment by richardfrost** [comment]
Hi @MrDizzyCam, thanks for the kind words! I don't believe that is a site I'm familiar with. Did it work before, or have you added a custom config for the site to support audio muting?

That specific message "Popup disabled by only mute audio" means that you have enabled the "Only mute audio" mode (Options page > Audio tab), which tells the extension to only run on sites that support audio muting. So, if you haven't added custom config for the site you mentioned, it will be turned off because it isn't recognized as a supported audio site. If you go to a supported site, such as YouTube, it should not show that message.

**Comment by MrDizzyCam** [comment]
Hi Richard,

Thank you for your reply. This is the first time I'm using this specific
site. It works perfectly on supposed sites. I did not do a custom add as it
looked a bit too technical for me. The filter worked on the subtitles when
the only audio mute option is not selected, but when selected nothing
worked. It seems like the site will have to be added, I will give it a go.

Best regards
Stephan

**Comment by richardfrost** [comment]
@MrDizzyCam Yeah, unfortunately it can be pretty technical to setup a custom site. Yeah, the "only mute audio" setting is used to turn off the filter on any site that doesn't have audio muting configured, so it sounds like it is working as expected. If you need help with adding support for that site I'm happy to try and help answer any questions you come across.

**Comment by MrDizzyCam** [comment]
Hi Richard,

Thanks so much for getting back to me!
I tried adding the site, but I got stuck at the breakpoint step (see the
attached image).
Could you help me out with adding support for this site?

Warm regards
Stephan

**Comment by richardfrost** [comment]
@MrDizzyCam Sorry, but I'm not seeing the image. I am happy to help though, if I can!

**Comment by MrDizzyCam** [comment]
Apologies I replied directly from Gmail, looks like the attachments doesn't go through then. Should be attached now. 
![Flixtor ](https://github.com/user-attachments/assets/3d0b4366-c587-44cf-9c70-661332b0dec3)

**Comment by richardfrost** [comment]
Thanks @MrDizzyCam. Without also seeing the page structure (Elements tab), I don't have enough information to make a complete guess, but as a starting point I'd probably guess it is something like this:

```json
{
  "flixtor.li": [{
      "className": "jw-text-track-container",
      "mode": "element",
      "subtitleSelector": "div.jw-text-track-cue",
      "tagName": "DIV"
  }]
}
```

You may need to adjust the domain name (`flixtor.li`), especially if it gets loaded in an `IFRAME` on the page (I don't have access to the site, so I can't say for sure it works).

**Comment by richardfrost** [comment]
Hi @MrDizzyCam, have you had a chance to try out what I shared?

**Comment by richardfrost** [comment]
@MrDizzyCam Just wanted to follow up and see if you had any other feedback on this. Thanks!
