### ISSUE TITLE
FUBO.TV

### ISSUE THREAD

**Issue by thaddeusrose** [FrostCo/AdvancedProfanityFilter#576]
It appears that the Firefox Profanity Filter for streaming FUBO.TV stopped working.   It works fine for Amazon Prime.
Let me know what you think.
Thank you.

**Comment by thaddeusrose** [comment]
Filter for FUBO was working fine for a long time then about 2 weeks ago it stopped working.
Please let know.
Thanks

**Comment by richardfrost** [comment]
Hello @thaddeusrose, thanks for reporting the issue. I just tried it on a couple videos and it seemed to be working for me. Could you share a channel/video that it isn't working for you on?

**Comment by thaddeusrose** [comment]
Either Firefox or Fubo made a change that is causing this problem.
Here is my system info.   Maybe this will help.
---
Windows 10
Firefox 131.0.2 (64-bit)

**Comment by richardfrost** [comment]
Sorry @thaddeusrose, but I'm still not seeing any issue with Firefox 131.0.3 (latest today) or Chrome (stable). Have you perhaps installed any new add-ons that might be causing a conflict? One title that I just tested with was `Mrs. Doubtfire`, right around 0:13:00.

If you can test that title and see if it works for you that would be great.

**Comment by thaddeusrose** [comment]
In Fubo it works fine in the Movie section.  I tested it with 2 movies and it works just fine.  However in a  TV series like Chicago Fire it does not work.

**Comment by richardfrost** [comment]
@thaddeusrose I don't see Chicago Fire when I search. I just tried it on some live TV (Cops Reloaded) and it seems to be working on both Chrome and Firefox for me there. Is Chicago Fire a live show, or on demand?

Do you have the subtitles hidden at all?

![image](https://github.com/user-attachments/assets/4022b1fc-8247-4993-890c-cbb8b7fbb15d)

If so, can you set it to "Show all" while we are trying to figure this out?

**Comment by thaddeusrose** [comment]
It appears to be working now.  Something changed or maybe it's just me.
Thanks for your quick response.

**Comment by richardfrost** [comment]
I'm glad it started working again for you. Do let me know if the issue comes back, or  you notice a new one. I'm going to close this for now since it seems to be working for you.
