### ISSUE TITLE
Vudu not muting

### ISSUE THREAD

**Issue by BE-Code** [FrostCo/AdvancedProfanityFilter#594]
#### :bug: Description

Muting is not happening on vudu anymore. I believe this is due to their domain changing to https://athome.fandango.com/

#### :twisted_rightwards_arrows: Steps To Reproduce

1. Go to vudu.com (redirects to https://athome.fandango.com/)
2. Sign in
3. Start a movie
4. Enable captions

#### :heavy_check_mark: Expected behavior

Tab is muted when captions contain profanity.

#### :computer: Details

- **Device:** M2 Macbook Air
- **OS:** MacOS 15.1.1
- **Browser:** Arc (Chromium)
- **Browser Version:** 1.69.0
- **Affected site(s):** vudu.com

**Comment by richardfrost** [comment]
Thanks for reporting the issue @BE-Code.

Could you give this updated config a try?

```json
{
  "athome.fandango.com": [
    {
      "displaySelector": "div#subtitleContainer > div",
      "iframe": true,
      "mode": "element",
      "subtitleSelector": "span.subtitles",
      "tagName": "DIV"
    }
  ]
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

For best results, make sure to remove any custom config used for testing like this once it has been included in the official update.

**Comment by richardfrost** [comment]
This has been added in version [4.0.0](https://github.com/FrostCo/AdvancedProfanityFilter/releases/tag/4.0.0). Feel free to respond here if you are having trouble with this site.
