### ISSUE TITLE
Disney Plus stopped muting in Chrome or Firefox

### ISSUE THREAD

**Issue by ricktheartist** [FrostCo/AdvancedProfanityFilter#595]
#### :bug: The filter is correctly replacing words in the subtitles but the audio is not muting. I have tried Chrome and Firefox, using both the Video volume method and the browser tab method.

- **Device:** MSI Laptop
- **OS:** Windows 11
- **Browser:** Chrome and Firefox
- **Browser Version:** Chrome; 131.0.6778.86, Firefox 132.0.2
- **Affected site(s):** disneyplus.com

**Comment by ricktheartist** [comment]
It worked fine last week so Disney changed something. :-(

**Comment by richardfrost** [comment]
Thanks @ricktheartist, it looks like they have updated their site quite a bit. I'll take a look and let you know what I find soon.

**Comment by richardfrost** [comment]
Can you give this config a try @ricktheartist 

```json
{
  "www.disneyplus.com": [
    {
      "className": "hive-subtitle-renderer-wrapper",
      "mode": "element",
      "subtitleSelector": "div.hive-subtitle-renderer-cue-window span.hive-subtitle-renderer-line",
      "tagName": "DIV",
      "videoSelector": "video#hivePlayer"
    }
  ]
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

For best results, make sure to remove any custom config used for testing like this once it has been included in the official update.

**Comment by bdc0der** [comment]
I had this exact same problem. This new config appeared to have fixed it, thanks.

**Comment by ricktheartist** [comment]
Yep, just tried it and it worked. Thank you!
