### ISSUE TITLE
Audio Muting for Kanopy

### ISSUE THREAD

**Issue by richardfrost** [FrostCo/AdvancedProfanityFilter#628]
### :movie_camera: [Kanopy](https://www.kanopy.com)

This issue is here for sharing updates and reporting issues related to this supported site. Feel free to leave a comment if you have any feedback to share.

**Comment by wrb42** [comment]
Hi,
I’m having issues with the audio muting feature on Kanopy. I’m running the extension on firefox on a mac running  iOS 26.4.2. The extension picks up words on the subtitles but the audio doesn’t mute. Any recommendations for a fix?
