### ISSUE TITLE
Audio Muting for Movies Anywhere

### ISSUE THREAD

**Issue by richardfrost** [FrostCo/AdvancedProfanityFilter#630]
### :movie_camera: [Movies Anywhere](https://moviesanywhere.com/)

This issue is here for sharing updates and reporting issues related to this supported site. Feel free to leave a comment if you have any feedback to share.

**Comment by richardfrost** [comment]
It was reported (#723) that filtering for Movies Anywhere has stopped working.

Here is an updated config that should work. If you have a chance to try it, please le me know how it goes:

```json
{
  "moviesanywhere.com": [
    {
      "mode": "elementChild",
      "parentSelector": "div.shaka-text-container",
      "subtitleSelector": "span.shaka-text-wrapper > span",
      "tagName": "div"
    }
  ]
}
```

To use this config, paste it into the Custom Sites area (Options page > Audio tab) and click the blue "SAVE" button underneath it. Then, make sure to refresh the tab for the video site (if you have it open still) and it will load this new configuration.

For best results, make sure to remove any custom config used for testing like this once it has been included in the official update.

**Comment by ampolisano** [comment]
It works! Thanks Richard :)
