### ISSUE TITLE
Audio Muting for PBS

### ISSUE THREAD

**Issue by richardfrost** [FrostCo/AdvancedProfanityFilter#636]
### :movie_camera: [PBS](https://www.pbs.org)

This issue is here for sharing updates and reporting issues related to this supported site. Feel free to leave a comment if you have any feedback to share.

**Comment by happycatholic** [comment]
Hi! I'm trying to use the Profanity Filter extension on PBS.org but it isn't working, at least not on any Masterpiece Theater shows I try to watch. Here's where I'm going - maybe it's not covered by the filter somehow? https://www.pbs.org/wgbh/masterpiece/ 
If you could help me out, that would be amazing! Thanks!

**Comment by happycatholic** [comment]
JMJ
Hi! Thanks so much for this! I followed your instructions and it's still not working on All Creatures Great and Small for me (that was actually the show I was having trouble with before - I've been testing it here at about 30:53 https://watch.montanapbs.org/video/episode-1-ifcgdb/ - I added religious exclamations to my filter word list like Lord, God, Jesus, etc. and they filter out everywhere else I've tried this up till now). But the filter was working on Miss Austen even before I added the updated config... Strange...

**Comment by richardfrost** [comment]
Thanks for sending the link to where you are watching it @happycatholic. It looks like you are watching it from `watch.montanapbs.org`, which is why the filter isn't working at all for you. Can you replace the last config with this new one and see if it works any better?

```json
{
  "watch.montanapbs.org": [
    {
      "displaySelector": "div.vjs-text-track-display > div",
      "iframe": true,
      "mode": "element",
      "subtitleSelector": "div.vjs-text-track-cue > div",
      "tagName": "DIV"
    }
  ]
}
```

**Comment by happycatholic** [comment]
JMJ
Hurray!! That did it!! Good catch - I'm grateful! Happy new year!!

**Comment by richardfrost** [comment]
I'm so glad it is working for you with that config @happycatholic. Take care, and hope you are having a great start to the new year!
