### ISSUE TITLE
Audio Muting for YouTube

### ISSUE THREAD

**Issue by richardfrost** [FrostCo/AdvancedProfanityFilter#661]
### :movie_camera: [YouTube](https://www.youtube.com)

This issue is here for sharing updates and reporting issues related to this supported site. Feel free to leave a comment if you have any feedback to share.

**Comment by nflnsr** [comment]
> Hi [@nflnsr](https://github.com/nflnsr),
> 
> Could you share the extension you are talking about? I'm not familiar with it. If you can share it I will take a look and see if I can tell what is going on with it.

here's the extension "Youtube Bilingual Subtitles"
https://chromewebstore.google.com/detail/youtube-bilingual-subtitl/gmgolpfecnlplngkidbjagmpgidbokck
